### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by xuxu0728** [jcustenborder/kafka-connect-cdc-oracle#2]
hello,I have tried your kafka-connect-cdc-mssql.I have tested the delay time when the data  inserted or updated in the sql server and the change consumed in the kafka,it is good.Maybe because it bases on the change tracking.But the delay time of kafka-connect-cdc-oracle which is based on xstream is longer.Since Oracle have Block Change Tracking, could we do kafla-connector-cdc-oracle based on block change tracking?
Thank you in advanced.Look forward to your reply.

**Comment by jcustenborder** [comment]
Hi @xuxu0728! I am not familiar with Block Change Tracking but looking at the documents I could see it causing a delay to when the data could be processed by xstreams. Unfortunately I don't have the experience with Block Change Tracking to tell you if you that is the cause.
